Ringkasan DOM adrian
fachrezamuslim/belajar-github-km4 pull request #39
Opened 2023-03-20 04:31 UTC by Adrian280602

2023-03-20 09:35 UTC, fachrezamuslim requested changes
salah

2023-03-20 09:47 UTC, Adrian280602 commented
> salah

sudah di perbaiki kak

2023-03-20 09:58 UTC, fachrezamuslim requested changes

2023-03-20 09:58 UTC, fachrezamuslim commented on learning/dom/index.html
> +        <td><a href="adrian.html">View</a></td>
salah

2023-03-20 10:08 UTC, Adrian280602 commented on learning/dom/index.html
> +        <td><a href="adrian.html">View</a></td>
> salah

baik kak, sudah saya perbaiki

2023-03-21 03:08 UTC, fachrezamuslim approved these changes

2023-03-21 03:09 UTC, merged